export { makeRumPublicApi } from './boot/rumPublicApi'
export type { RumPublicApi } from './boot/rumPublicApi'
export type { RumInitConfiguration, RumConfiguration } from './domain/configuration/configuration'
export type { RumEvent } from './rumEvent.types'
export type { RawRumEvent } from './rawRumEvent.types'
